[package]
name = "magnet_example"
version = "0.1.0"
authors = ["Stefano Cobianchi <stefano.cobianchi@me.com>"]

[dependencies]
hyper = "*"
liquid = "*"
diesel = "*"
diesel_codegen = "*"
dotenv = "*"
dotenv_macros = "*"
magnet_core = "0.0.1"
magnet_more = "0.0.1"
magnet_app = "0.0.1"
